/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

void delay(void);

int main(void)
{
	/*
	 * Procedure:
	 * 1. Enable Peripheral Clock for AHB1
	 * 2. Configure the PD15 pin as output
	 * 3. Write 1 to pin PD15
	 */

	uint32_t *RCC_AHB1_ADDR = (uint32_t*) 0x40023830;
	uint32_t *GPIOD_MODE_REG = (uint32_t*) 0x40020C00;
	uint32_t *GPIOD_OUTPUT_REG = (uint32_t*) 0x40020C14;
	//enable Peripheral Clock for AHB1
	*RCC_AHB1_ADDR |= 1 << 3;
	//clear the 30th and 31st bit
	*GPIOD_MODE_REG &= ~(3 << 30);
	//configure PD15 as output
	*GPIOD_MODE_REG |= 1 << 30;

	while(1){
		//turn LED on
		*GPIOD_OUTPUT_REG |= 1 << 15;
		delay();
		//turn LED off
		*GPIOD_OUTPUT_REG &= ~(1 << 15);
		delay();
	}
}

void delay(void){
	for(int i = 0; i< 1000000; i++) {}
}
